- model/src/lib.rs
- src/domain/handler.rs
- src/domain/sql_backend_handler.rs
- src/infra/tcp_backend_handler.rs
Tests are barebones and are dependant of the list_users_request
(delete_user_request_test will fail if list_users_request fails)
> Implementation of the delete_user_request.

- Dockerfile
> Fix dockerfile start command

- app/src/api.rs
- app/src/app.rs
- app/src/cookies.rs
- app/src/lib.rs
- app/src/login.rs
- app/src/user_details.rs
- lldap_config.toml
- model/src/lib.rs
- src/domain/handler.rs
- src/domain/sql_backend_handler.rs
- src/infra/auth_service.rs
- src/infra/tcp_api.rs
- src/infra/tcp_backend_handler.rs
- src/infra/tcp_server.rs
The new API endpoint "/api/user/<user_id>" returns the user's details, and is accessible by both admins and the user themselves.
> Add a way to view a user's details

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- app/queries/create_user.graphql
- app/queries/get_user_details.graphql
- app/queries/update_user.graphql
- app/src/app.rs
- app/src/create_user.rs
- app/src/user_details.rs
- app/src/user_table.rs
- export_schema.sh
- schema.graphql
- server/Cargo.toml
- server/src/domain/handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_tables.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/tcp_backend_handler.rs
Implement the "update user details" from #11 by making user details editable.
> User interface

- Dockerfile
> Fix the Docker start command

- app/index.html
- app/queries/delete_user.graphql
- app/src/components/delete_user.rs
- app/src/components/mod.rs
- app/src/components/user_table.rs
- app/src/infra/mod.rs
- app/src/infra/modal.rs
- schema.graphql
- server/src/infra/graphql/mutation.rs
This comes with a confirmation pop-up to make sure that the user should be deleted :)
> Add a way to delete a user

- schema.graphql
- server/src/domain/handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/tcp_backend_handler.rs
And add a couple of missing graphQL methods
> Add support for memberOf in LDAP interface

- app/src/components/add_group_member.rs
- app/src/components/add_user_to_group.rs
- app/src/components/change_password.rs
- app/src/components/create_group.rs
- app/src/components/create_user.rs
- app/src/components/delete_group.rs
- app/src/components/delete_user.rs
- app/src/components/group_details.rs
- app/src/components/group_table.rs
- app/src/components/login.rs
- app/src/components/logout.rs
- app/src/components/remove_user_from_group.rs
- app/src/components/user_details.rs
- app/src/components/user_details_form.rs
- app/src/components/user_table.rs
- app/src/infra/api.rs
- app/src/infra/common_component.rs
- app/src/infra/mod.rs
This makes the implementation more standard, and regularizes the use of `error`, `task`, `props` and so on.
> Implement a CommonComponent to refactor common functionality in app components

- README.md
- example_configs/keycloak.md
- server/src/infra/ldap_handler.rs
- server/src/infra/ldap_server.rs
This should help with KeyCloak support.
> ldap: Add support for createTimestamp and modifyTimestamp

- Dockerfile
> docker: Fix pkg copy

- Dockerfile
Looks like this was accidentally left out so it was 404ing
> copy style.css into the container

- example_configs/jitsi_meet.conf
The config was missing the search base, leading to wrong queries.
> jitsi: Add search base

- README.md
- example_configs/bookstack.env.example
- example_configs/bookstack.example
I have added lldap to bookstack. Although very easy, I thought it appropriate too add the example here 
/B
> Add bookstack example

- server/src/domain/error.rs
- server/src/domain/handler.rs
- server/src/domain/opaque_handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/sql_tables.rs
- server/src/infra/auth_service.rs
- server/src/infra/configuration.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/sql_backend_handler.rs
- server/src/infra/tcp_backend_handler.rs
Note that if there was a non-lowercase user already in the DB, it cannot
be found again. To fix this, run in the DB:
sqlite> UPDATE users SET user_id = LOWER(user_id);
Fixes #125
> domain: introduce UserId to make uid case insensitive

- app/index.html
- app/src/components/app.rs
> Add a footer

- .github/workflows/rust.yml
- .gitignore
- app/src/components/reset_password_step2.rs
- app/src/infra/api.rs
- server/src/infra/auth_service.rs
Fixes #135 and improves error reporting for emails.
> Fix password reset

- example_configs/jellyfin.md
> examples: Add Jellyfin config.

- server/src/infra/ldap_handler.rs
> server: Handle "1.1" special attribute

- server/src/infra/ldap_handler.rs
> ldap_handler: Reports groups as groupOfNames as well

- server/src/infra/ldap_handler.rs
> server: allow non-admin user to do limited searches

- app/src/components/app.rs
Fixes #142 
I tried to make it work with some flex boxes, but it's outside my area of expertise and I failed. If anyone wants to take a shot at it, b e my guest.
> app: add bottom padding to avoid overlap with the footer

- README.md
> readme: Make compatible services more explicit

- docs/architecture.md
> docs: update architecture doc

- server/src/infra/ldap_handler.rs
Resolves #158
Review very welcome, I'm new to rust and found this challenging to write
Doesnt introduce regressions, but test cases are needed (I just don't want to write them 🙃 )
I haven't even run this against an authentik instance yet, I'll probably make a docker-compose for testing against one
> Improve Authentik Support by handlign wildcards + DN

- README.md
> readme: fix env variable

- server/src/domain/handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/tcp_backend_handler.rs
The "memberOf" filter was already supported, but not the attribute.
Fixes #179
> ldap: add support for memberOf attribute

- server/src/infra/ldap_handler.rs
Nextcloud searches for users by specifying the entire user DN as the
scope. This commit adds support for these specific scopes.
> ldap: handle full scope searches

- example_configs/wg_portal.env.example
~~however I didn't get it working with usernames too, trying to do that right now~~
Nevermind, the example I was sent was missing a `)` :) everything working now
> add wg-portal example

- Cargo.lock
- Cargo.toml
- app/Cargo.toml
- auth/Cargo.toml
- server/Cargo.toml
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/sql_tables.rs
- server/src/infra/jwt_sql_tables.rs
- server/src/infra/sql_backend_handler.rs
> sqlx: update dependency and protect against injections

- server/src/domain/sql_backend_handler.rs
The confusion of display_name caused every user to be called like the
first group they belonged to.
> server: Disambiguate list_users query

- .github/workflows/Dockerfile.ci
The user 1000 already created but not used due wrong env.
> set lldap to run rootless, using user 1000

- Cargo.lock
- server/Cargo.toml
- server/src/domain/handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_tables.rs
- server/src/infra/auth_service.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/tcp_backend_handler.rs
That will enable NextCloud support.
> Add UUID fields for users and groups

- .github/workflows/docker-build.yml
From my test it just shaved about 2~3 mnites. Not so impressive.
> Add cache and sccache

- Cargo.lock
- server/src/domain/sql_backend_handler.rs
Fixes https://github.com/nitnelave/lldap/issues/214
> Fix handling of users with no groups

- server/src/infra/ldap_handler.rs
Fixes https://github.com/nitnelave/lldap/issues/189
> server: Make objectClass matching case-insensitive

- CHANGELOG.md
- Cargo.lock
- README.md
- app/Cargo.toml
- server/Cargo.toml
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_tables.rs
- server/src/infra/auth_service.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/main.rs
Fixes https://github.com/nitnelave/lldap/issues/227
> Add a strict readonly group and migrate the readonly group to password manager

- .github/workflows/Dockerfile.ci.alpine
Tried new image, missing `bash` package needed by entrypoint.sh
> add bash, entrypoint deps.

- .github/workflows/Dockerfile.ci
- .github/workflows/Dockerfile.ci.alpine
- docker-entrypoint.sh
Following #230 
1. Add gosu package
2. Modify entrypoint to chown `/app` and `/data` to UID:GID
> Enabling UID:GID

- README.md
Currently there is significant difference `:stable` tag and `:latest` tag, as people behaviour of using `:latest`, give notice that latest prone to break, changes.
1. Add compose sample for `:latest`.
> More info about `:latest` tag and permissions

- .github/workflows/docker-build-static.yml
- Cargo.lock
- migration-tool/Cargo.toml
- migration-tool/src/lldap.rs
- server/Cargo.toml
- server/src/infra/ldap_server.rs
> server: switch from OpenSSL to Rustls

- README.md
- example_configs/lldap.service
- lldap_config.docker_template.toml
- server/src/domain/sql_tables.rs
> Misc small fixes.

- .github/workflows/docker-build-static.yml
- server/src/infra/ldap_handler.rs
> Stop returning duplicate "dn" attribute in LDAP search results.

- README.md
Found a typo in the README.md. Here is a quick fix :D
> fixed typo on jitsi

- README.md
- example_configs/airsonic-advanced.md
Have tested this and is working for me.
> Airsonic-Advanced

- server/src/domain/sql_backend_handler.rs
> server: Fix query building of chained ands/ors

- server/src/infra/ldap_server.rs
> server: Add support for PKCS1 keys

- server/src/domain/sql_backend_handler.rs
> server: Silence error message when creating DB

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- .github/workflows/docker-build-static.yml
Seems we oversight the download path of js and fonts.
https://github.com/nitnelave/lldap/issues/310
> Fix download assets js and fonts

- README.md
- example_configs/hedgedoc.md
working configuration for https://hedgedoc.org/ include of filter for members of group
> Configuration for hedgedoc

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- Cargo.lock
- Dockerfile
- server/Cargo.toml
- server/src/infra/cli.rs
- server/src/infra/healthcheck.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/logging.rs
- server/src/infra/mod.rs
- server/src/infra/tcp_server.rs
- server/src/main.rs
> server: implement healthcheck

- server/src/infra/ldap_handler.rs
> ldap: add entryUUID to the default fields

- example_configs/dokuwiki.md
fixed a constant error message in LLDAP log.
> fixed mistake

- server/src/domain/mod.rs
- server/src/domain/sql_migrations.rs
- server/src/domain/sql_tables.rs
> server: Start versioning the DB schema

- .config/nextest.toml
- server/src/domain/ldap/error.rs
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/mod.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/mod.rs
- server/src/infra/ldap_handler.rs
Split it into several files, move them into the domain folder, introduce
`LdapError` for better control flow.
> Refactor ldap_handler

- server/src/domain/handler.rs
- server/src/domain/mod.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/tcp_backend_handler.rs
- server/src/main.rs
> server: refactor sql backend handler

- server/src/infra/graphql/api.rs
> server: increase max payload size to 16MB

- server/src/domain/handler.rs
- server/src/infra/ldap_handler.rs
> server: Add support for creating a user through LDAP

- lldap_config.docker_template.toml
> Ensure generated JWT doesn't include quotation mark

- Cargo.lock
- app/Cargo.toml
- app/src/components/reset_password_step1.rs
- app/src/infra/api.rs
- server/src/infra/auth_service.rs
Instead of just username
Fixes #267
> server,app: Add support for resetting your password with email

- README.md
- example_configs/zendto.md
working config for https://zend.to/
> added example config for zendto

- example_configs/kanboard.md
Added a working example config for [kanboard](https://kanboard.org/)
> Kanboard example config

- server/src/infra/auth_service.rs
- server/src/infra/mail.rs
- server/src/main.rs
> fix: use async api for email sending

- server/src/infra/graphql/api.rs
- server/src/main.rs
Resolves following suggestions: https://github.com/nitnelave/lldap/actions/runs/3541147776/jobs/5945053484
> server: follow clippy's suggestions

- server/src/infra/tcp_server.rs
Align path building on advice in [docs](https://doc.rust-lang.org/stable/std/path/struct.PathBuf.html#examples)
> server: prefer immutable path

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .dockerignore
- .gitignore
Fixes #331 
The dockerfile could probably be optimized - i just tinkered until i got something that wants to work out the box. the cargo install step is pretty hefty, so i COULD try to tinker with making that a separate layer as early as possible to help cache it, but i don't think it's too important given this shouldn't change often at all.
> Add devcontainer

- .github/workflows/docker-build-static.yml
add command to fetch the libraries and fonts that missing from on zipped web release.
> fetch missing web components

- example_configs/gitea.md
Not extensively tested, but group/team sync seems to work in Forgejo.
> Gitea: add additional attributes and group sync

- server/src/domain/handler.rs
- server/src/domain/ldap/user.rs
- server/src/domain/model/groups.rs
- server/src/domain/model/jwt_refresh_storage.rs
- server/src/domain/model/jwt_storage.rs
- server/src/domain/model/password_reset_tokens.rs
- server/src/domain/model/users.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_migrations.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/sql_tables.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/domain/types.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/sql_backend_handler.rs
With these 2 commits, the integration with mysql/postgres is working.
It was only tested by hand, I didn't set up an automated test.
It's completely backwards-compatible with SQlite.
Fixes #87
> Improve support for MySQL/Postgres

- README.md
- example_configs/wikijs.md
Appreciate the help in Discord, hopefully this will help the next person who struggles like I did.  
As always @nitnelave thanks for all your work on this, sorry about posting in the wrong channel and bothering you with what ended up being a PEBKAC error!
> Wikijs Example

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- .github/workflows/Dockerfile.dev
- .github/workflows/docker-build-static.yml
As the building binary pretty much stable, we dont need separate 3 job target. This PR merge 3 job into one by using matrix
* https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
* only binary building affected
* add minimal postgres and mysql integration (up and run), selfcheck
* Selfcheck will throw err if something bad happen
> Just another CI update for easier maintain

- Cargo.lock
- server/Cargo.toml
> server: update sea-orm dependency

- README.md
- example_configs/dex_config.yml
> Dex configuration

- example_configs/gitea.md
test on:
- LLDAP 0.4.1
- Gitea 1.18.3
> Add example for Gitea's simple auth mode

- server/src/domain/sql_migrations.rs
- server/src/domain/sql_tables.rs
> server: allow NULL for display_name

- server/src/domain/handler.rs
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/ldap_handler.rs
> server: Add support for SubString ldap filter

- app/src/components/app.rs
- app/src/components/login.rs
- app/src/infra/api.rs
- server/src/infra/auth_service.rs
- server/src/infra/tcp_server.rs
> Support disabling password reset

- server/src/infra/mail.rs
> server: add content-type header to the email

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- Dockerfile
> docker: fix healthcheck

- README.md
- example_configs/nexus.md
> example_configs,nexus: Add example for Sonatype Nexus Repository Manager 3

- server/src/domain/ldap/user.rs
- server/src/infra/ldap_handler.rs
> server: return groups in memberof by cn instead of uid

- server/src/domain/sql_migrations.rs
- server/src/domain/sql_tables.rs
> server: ensure first/last name nullable, make avatar long blob in DB

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- .github/workflows/docker-build-static.yml
- Cargo.lock
- Cargo.toml
- Dockerfile
- set-password/Cargo.toml
- set-password/src/main.rs
> lldap_set_password: create the new tool

- docs/database_migration.md
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/main.rs
New command to test a dataabase url and ensure the schema exists and is up to date. Update migration docs to include usage of this command
> Create schema command

- README.md
- docs/architecture.md
> README: Add details about other DBs, migrations

- app/build.sh
- app/static/main.js
- server/src/infra/tcp_server.rs
> app: server uncompressed WASM to webkit browsers

- .github/workflows/docker-build-static.yml
On main, we need to re-build and push it.
> github: Don't skip rebuilding a docker image on main because it was built on a branch

- app/src/components/app.rs
- server/src/infra/auth_service.rs
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
> Fix password reset redirection

- example_configs/nextcloud.md
Add email attribute, otherwise nextcloud will not set the email address in users profile
> Add email attribute

- .github/workflows/docker-build-static.yml
cut relies on the string being a fixed length, which is subject to change in the  future
> Use jq in CI to extract json deterministically

- .github/workflows/docker-build-static.yml
* Fixing service db, sometimes job throwing error race condition `lldap healthcheck run before db ready`
> db-service-start

- server/src/infra/ldap_server.rs
Tested locally using [self-signed certificate](https://www.scottbrady91.com/openssl/creating-elliptical-curve-keys-using-openssl).
Resolves #525
> feat: support ec private keys

- server/Cargo.toml
- server/src/infra/healthcheck.rs
- server/src/infra/ldap_server.rs
> healthcheck: check that the server's certificate is the one in the config

- server/src/infra/configuration.rs
To address https://github.com/lldap/lldap/issues/504#issuecomment-1506837675
> server: Make key_seed a secret value

- example_configs/opnsense.md
Added an example configuration for using LLDAP in OPNsense.
> Add OPNsense example config.

- .github/workflows/Dockerfile.ci.alpine
- .github/workflows/Dockerfile.ci.debian
- .github/workflows/docker-build-static.yml
- Cargo.lock
- Dockerfile
- README.md
- app/Cargo.toml
- auth/Cargo.toml
- migration-tool/Cargo.toml
- server/Cargo.toml
- set-password/Cargo.toml
> cargo: set metadata for publishing crates

- example_configs/dokuwiki.md
This caused quite some head scratching for me ;)
> Fix Dokuwiki configuration

- example_configs/grafana_ldap_config.toml
> example_configs: fix grafana config

- README.md
- example_configs/mealie.md
Tested and working configuration for [Mealie](https://github.com/hay-kot/mealie)
> Add Mealie configuration example.

- Cargo.lock
- server/Cargo.toml
- server/src/domain/handler.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/mod.rs
- server/src/domain/model/group_attribute_schema.rs
- server/src/domain/model/user_attribute_schema.rs
- server/src/domain/model/user_attributes.rs
- server/src/domain/model/users.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/domain/types.rs
- server/src/infra/access_control.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
> Use attribute schema at the LDAP/GraphQL layers

- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/graphql/query.rs
> graphql: sort the groups before returning them

- server/src/infra/cli.rs
- server/src/infra/mail.rs
> Smtp encryption

- server/src/infra/ldap_handler.rs
> server: Allow creating a user with multiple objectClass

- set-password/src/main.rs
> set_password: Properly parse the URL, support trailing slashes

- Cargo.lock
- server/Cargo.toml
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/infra/mail.rs
- server/src/infra/tcp_server.rs
> server: Add a message ID to sent emails

- example_configs/jellyfin.md
> example_configs: Add Jellyfin Password change

- app/index.html
Adds messages to detect if JavaScript and WASM are supported and enabled. 
Fixes: #636
> Incompatible browser detection

- app/index.html
- app/index_local.html
> app: Add the JS warnings to index_local.html

- example_configs/thelounge.md
Example for https://thelounge.chat/
> Add thelounge.md

- README.md
- example_configs/zulip.md
All used configuration examples are tested and working.
There may be some more configurable options, but I think my example makes use of most of them.
I am aware that my spelling might be a bit off, so feel free to change anything you don't like.
> example_configs: Add example config for zulip

- server/src/infra/ldap_handler.rs
This should enable support for VMware vCenter.
> server: Add support for querying the OUs

- app/src/components/user_details_form.rs
> app: Add a button to clear the avatar

- server/src/main.rs
> server: Only create the default admin if there are no admins

- README.md
- example_configs/proxmox.md
This is my attempt at the proxmox configuration example, I think it's a bit more opinionated than my previous examples. Open to feedback on all aspects of the document. Particularly unsure if the ACL section is a little too verbose, or possibly overlaps with Proxmox's own documentation too much.
> Add proxmox example config

- schema.graphql
- server/src/infra/graphql/query.rs
> server: return attributes in graphql

- schema.graphql
- server/src/domain/model/group_attributes.rs
- server/src/domain/model/groups.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/types.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
> server: return user-defined attributes for groups in graphql

- server/src/domain/handler.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/ldap_handler.rs
> Add support for writing attribute values in domain

- server/src/domain/handler.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/access_control.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/test_utils.rs
- server/src/main.rs
> Add support in domain for creating attributes, and setting group attributes

- schema.graphql
- server/src/domain/handler.rs
- server/src/domain/types.rs
- server/src/infra/access_control.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/test_utils.rs
> server: Add graphql support for creating/deleting attributes

- server/src/infra/ldap_server.rs
This implements rudimentary support for the Paged
Results Control.
No actual pagination is performed, and we ignore
any requests for specific window sizes for paginated results.
Instead, the full list of search results is returned for any searches, and a control is added to the
SearchResultsDone message, informing the client that there is no further results available.
> Basic support for Paged Results Control (RFC 2696)

- example_configs/dokuwiki.md
without this fix the admin user can not do any kind of admin task in dokuwiki
> working admin user for dokuwiki

- .github/workflows/docker-build-static.yml
- docs/database_migration.md
- server/src/infra/auth_service.rs
- server/src/infra/sql_backend_handler.rs
- server/src/infra/tcp_backend_handler.rs
Otherwise, logging out doesn't actually blacklist the JWT.
Fixed #721
> server: Add JWTs to the DB

- README.md
- example_configs/jenkins.md
Created tutorial and sample config for Jenkins for LLDAP
> Jenkins config for LLDAP

- server/src/domain/handler.rs
- server/src/infra/graphql/mutation.rs
> server: Prevent regular users from modifying non-editable attributes

- server/src/infra/graphql/mutation.rs
> server: Disallow deleting hardcoded attributes

- example_configs/bootstrap/bootstrap.sh
Mitigate #745 related behavior of `bootstrap.sh`
> example_configs(bootstrap.sh): Add check is user in group

- README.md
- example_configs/kasm.md
I created an example of how to use kasm with lldap
> example for kasm config

- README.md
- example_configs/gitlab.md
I'm very new to LDAP, so I hope this is all correct.
> Add example config for GitLab

- README.md
This dissussion #765 shown different behaviour than it expected. Add more description to it.
> Add pre packaged repo

- README.md
- example_configs/zitadel.md
Finally found a sso solution that baby can use 😆
> Add example conf for zitadel

- README.md
- example_configs/home-assistant.md
- example_configs/lldap-ha-auth.sh
Updated the homeassistant script so it can support assigning users to internal regular and admin groups
> Example homeassistant update

- lldap_config.docker_template.toml
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/main.rs
> server: Add an option to force reset the admin password

- example_configs/zitadel.md
- fixed `Userbase` attribute
- added `Preferred username attribute`
- added `Automatic creation`
> docs(zitadel): make the doc more comprehensive

- example_configs/mailserver.md
don't know exactly where i past. This is my compose file 
#642
> Dovecot configuration for docker-mailserver 

- .github/workflows/docker-build-static.yml
Playing with tag is dangerous, only switch up the build.
> switch up build steps

- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/infra/ldap_handler.rs
> server: add support for entryDN

- server/src/domain/sql_migrations.rs
- server/src/domain/sql_tables.rs
> server: add a unique index to the memberships

- README.md
- example_configs/grocy.md
Added a sample configuration for [Grocy](https://grocy.info/)
> Added grocy example config

- .github/workflows/Dockerfile.dev
- Cargo.lock
- server/Cargo.toml
- server/src/infra/ldap_handler.rs
This will fix the issue with some unhandled controls.
> server: update ldap3_proto dependency

- server/src/domain/deserialize.rs
- server/src/domain/handler.rs
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/mod.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
This should fix #763  and allow filtering by custom attribute values.
> server: Serialize attribute values when searching

- README.md
- generate_secrets.sh
- lldap_config.docker_template.toml
Deprecate key_file in favor of key_seed, add a script to generate the secrets
> docs: Misc updates

- Cargo.lock
- app/src/components/change_password.rs
- app/src/components/create_user.rs
- app/src/components/login.rs
- app/src/components/reset_password_step2.rs
- auth/Cargo.toml
- auth/src/lib.rs
- auth/src/opaque.rs
- migration-tool/src/lldap.rs
- server/Cargo.toml
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/types.rs
- server/src/infra/auth_service.rs
- server/src/infra/ldap_handler.rs
- server/src/main.rs
- server/tests/common/auth.rs
- set-password/src/main.rs
> server: Move the definition of UserId down to lldap_auth

- README.md
- example_configs/maddy.md
Added an example configuration for the [Maddy Mail Server](https://maddy.email/)
> Added maddy example config

- schema.graphql
- server/src/domain/schema.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
And make sure that we only request the schema once per top-level query
> server: Add the attribute schema to the attributes in graphql

- server/src/infra/ldap_handler.rs
> server: don't error on global searches if only one side fails

- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/infra/database_string.rs
- server/src/infra/mod.rs
- server/src/main.rs
> server: Treat the database password as a secret

- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
> server: Only call expand_attributes at most once per request

- server/src/main.rs
i don't THINK this was meant to be left :)
> server: remove debug print

- app/src/components/change_password.rs
- app/src/components/create_group.rs
- app/src/components/create_user.rs
- app/src/components/form/field.rs
- app/src/components/form/mod.rs
- app/src/components/form/static_value.rs
- app/src/components/form/submit.rs
- app/src/components/login.rs
- app/src/components/reset_password_step2.rs
- app/src/components/user_details_form.rs
Most of the spots switched to the new components, though the login form didn't quite fit with the new components. Instead of forcing it to fit i left it out for the time being.
fixes #812
> app: update forms to use new components

- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
When the database's collation is not "C", the DB order is not the same as the Rust order. As such, asserting that the elements are in increasing order fails. However, since both queries get the order from the database, they should be in the same order.
With too many users, the query had a giant filter `IN (u1, u2, u3, ...)`. In PostgreSQL, we can pass the users as an array instead, but that doesn't work with SQLite. Instead, we repeat the filter from the previous query to get the same users/groups, as a subquery.
> server: Fix panic due to database collation

- schema.graphql
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/infra/access_control.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/ldap_handler.rs
Namely, interaction with LDAP filters, and graphql mutation functions.
Part of #67
> Add missing object class functionalities

- app/src/infra/functional.rs
> app: Fix GetDetails rendering loop in avatar

- app/src/infra/api.rs
- server/src/infra/auth_service.rs
Otherwise, caching can become an issue. Also, it's not an idempotent request.
Fixes #704
> app,server: Switch /reset/step1 to a POST request

- example_configs/dokuwiki.md
Just an addition to the dokuwiki documentation
> docs: mentioned dokuwiki authchained plugin

- server/src/domain/ldap/user.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_migrations.rs
- server/src/domain/sql_tables.rs
- server/src/domain/sql_user_backend_handler.rs
> server: Add missing unique indices on lowercase email/group names, fix memberof lookup

- app/src/components/reset_password_step1.rs
> app: Improve the email reset message

- .github/workflows/Dockerfile.dev
> github: Update dev container to add FreeBSD target

- server/src/domain/sql_user_backend_handler.rs
> server: Fix user search for multiple memberOf

- example_configs/nextcloud.md
Add a example of group filter.
> Update nextcloud.md - add a example of group filter

- README.md
- example_configs/carpal.md
This PR adds an example configuration for the [Carpal](https://github.com/peeley/carpal/tree/master) WebFinger server.
> Add Carpal example configuration

- README.md
- example_configs/prosody.md
Hi,
I added an example for [prosody](https://prosody.im/doc/modules/mod_auth_ldap)
> Prosody example

- README.md
- example_configs/netbox.md
I noticed that there wasn't an example config for Netbox. It took me about 20 minutes to get this working and I figured I would add it so others have an easier time. Any modifications are welcome!
> Adds example configuration for Netbox

- server/src/domain/handler.rs
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
Instead of just doing a schema check, this actually looks for users that have a value for this attribute.
Fixes #950
> server: Fix implementation of attribute present filter

- server/src/infra/configuration.rs
> server: Fix compilation on Windows

- server/src/infra/mail.rs
> server: Mask the details of SMTP errors, sleep when failing to send an email

- example_configs/freebsd/freebsd-install.md
Use ">" will clean up whole rc.conf directly. Don't ask me why I notice this :).
> Use sysrc in FreeBSD install instruction

- lldap_config.docker_template.toml
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/main.rs
> server: Allow password reset every time the server starts

- Cargo.lock
- auth/Cargo.toml
- auth/src/lib.rs
- server/Cargo.toml
- server/src/domain/types.rs
- server/src/infra/configuration.rs
- server/src/infra/database_string.rs
- server/src/infra/mail.rs
- server/src/infra/tcp_server.rs
And use derive_more more liberally to simplify the impls
> server: Simplify the debug print of various structs

- server/src/infra/ldap_handler.rs
> server: detect anonymous binds and return a correct error

- example_configs/pam/README.md
- example_configs/pam/nslcd.conf
Remove `is-unix-user` mentions, add note about using nightly, fix typo for passwd gid entry.
> Update the documentation for PAM integration

- example_configs/radicale.md
3.2.4 hasn't actually released yet, so maybe wait for this to be merged.
> example_configs: Update Radicale guide with configuration for Radicale 3.2.4

- app/Cargo.toml
- app/queries/get_user_attributes_schema.graphql
- app/queries/get_user_details.graphql
- app/src/components/avatar.rs
- app/src/components/create_user.rs
- app/src/components/form/attribute_input.rs
- app/src/components/form/date_input.rs
- app/src/components/form/file_input.rs
- app/src/components/form/mod.rs
- app/src/components/user_details.rs
- app/src/components/user_details_form.rs
- app/src/infra/functional.rs
- app/src/infra/mod.rs
- app/src/infra/schema.rs
- app/src/infra/tooltip.rs
- server/src/infra/graphql/query.rs
> UI: User attributes form

- example_configs/grafana_ldap_config.toml
Use `dc=com` as the same as the default DN.
> Update base DN in grafana_ldap_config.toml

- app/Cargo.toml
- app/queries/get_group_details.graphql
- app/queries/update_group.graphql
- app/src/components/app.rs
- app/src/components/group_details.rs
- app/src/components/group_details_form.rs
- app/src/components/mod.rs
- server/src/infra/graphql/mutation.rs
> app: Add support for group attributes

- app/Cargo.toml
- app/queries/get_group_details.graphql
- app/queries/update_group.graphql
- app/src/components/app.rs
- app/src/components/group_details.rs
- app/src/components/group_details_form.rs
- app/src/components/mod.rs
- app/src/infra/api.rs
- server/src/infra/graphql/mutation.rs
It was still using get, but should have used post
> app: fix password reset probing

- server/src/infra/configuration.rs
> server: improve key_seed warning

- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/infra/ldap_handler.rs
> server: return custom attributes when asked for all attributes

- app/queries/create_group.graphql
- app/queries/get_group_attributes_schema.graphql
- app/src/components/create_group.rs
- app/src/components/create_user.rs
- app/src/components/group_details_form.rs
- app/src/components/user_details_form.rs
- app/src/infra/form_utils.rs
> app: Allow custom attributes in group creation

- server/src/infra/ldap_handler.rs
> server: Fix missing lowercasing when changing passwords through LDAP

- example_configs/vaultwarden.md
> update to vaultwarden_ldap_sync:2.0.2

- server/src/infra/auth_service.rs
> server: Correctly handle attempts to probe for password resets

- server/src/infra/graphql/mutation.rs
> server: Correctly handle removal of the display_name attribute

- server/src/infra/ldap_handler.rs
- server/src/infra/ldap_server.rs
When clients keep long-running LDAP sessions, the logs get endlessly buffered, turning into a slow memory leak. This change removes the session-long span, in favor of adding a session UUID to identify requests from the same UUID.
Sample non-verbose log:
```
2024-11-04T20:20:55.440854116+00:00  INFO     LDAP request [ 646ms | 100.00% ] session_id: d27e7230-19fe-4697-bb7c-a0ac732482d3
2024-11-04T20:20:55.442111783+00:00  INFO     ┕━ ｉ [info]: Login attempt for "admin"
2024-11-04T20:20:56.087854432+00:00  INFO     LDAP request [ 80.2ms | 100.00% ] session_id: d27e7230-19fe-4697-bb7c-a0ac732482d3
2024-11-04T20:20:56.169710414+00:00  INFO     LDAP request [ 23.9µs | 100.00% ] session_id: d27e7230-19fe-4697-bb7c-a0ac732482d3
2024-11-04T20:20:56.169840501+00:00  INFO     ｉ [info]: LDAP session …
```
> server: Remove session-wide logging, add session_uuid to message logs

- example_configs/pam/README.md
Custom attributes appear to all just work through the web ui in 0.6.0
> Update pam example for release 0.6.0

- server/src/domain/sql_migrations.rs
Neither supports limits, but we can delete all the duplicate memberships and re-insert a single one.
Fixes #1045
> server: Fix schema migration from v8 for sqlite and postgres

- README.md
- example_configs/hashicorp-vault.md
Fixed my pull request, sorry about the last one.
Anyway, I had to redeploy my vault cluster in my homelab and not having this documented caused me quite the headache. I finally got it working and thought I'd document it for everyone else. Any modifications are welcome!
> Adds HashiCorp Vault configuration

- .github/workflows/docker-build-static.yml
- README.md
- server/src/infra/access_control.rs
- server/src/infra/cli.rs
- server/src/infra/configuration.rs
- server/src/infra/tcp_server.rs
- server/src/main.rs
- server/tests/common/env.rs
- server/tests/common/fixture.rs
Similarly, don't create the admin if the password is not given
> Prevent starting up if the JWT secret is not given

- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/infra/ldap_handler.rs
Extends the generated UserRequestFilter with an OR'ed clause for the attribute value in both it's original case and lowercased.
So, where the search was previously `(attr=LOWERCASE(value))` it is now basicly `(|(attr=LOWERCASE(value))(attr=value))`. This matters, because the DB search is case sensitive, so it was only possible to resolve attributes with lowercase values. Original behavior is still compatible.
The `value => value_lc` changes are just variable renaming. The `value` variable, was redefined as a lowercased version of the original `value` variable, and was therefore shadowing the original. As I need the original unmodified value, I thought it best to restore that, and avoid the shadowing.
Fixes issue #1073.
> server: include preserved case in user attribute value search (#1073)

- app/Cargo.toml
- server/src/infra/ldap_handler.rs
Some legacy issues raised sporadically by clippy.
> Clippy fixes

- server/src/infra/ldap_handler.rs
From https://github.com/lldap/lldap/pull/1094 :
Adds support for the OID whoami extension(?). I've tested this with `ldapwhoami -H ldap://127.0.0.1:3890 -x -D "uid=admin,ou=people,dc=example,dc=com" -w password`, and works without any issues.
This has also been tested in combination with Stalwart mail server :)
> server: Adds support for whoamiOID

- crates/domain/src/requests.rs
- crates/domain/src/types.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/model/group_attributes.rs
- server/src/domain/model/user_attributes.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
Preparation for storing the actual types for each value, which will repurpose the AttributeValue name.
> domain: rename AttributeValue to Attribute

- README.md
Added a link to my Discord -> LLDAP rank sync bot, tried to follow your existing link structure.
> Discord Integration

- example_configs/stalwart.md
Failed at getting Docker Mailserver and Maddy working, so I wrote a config for Stalwart Mailserver instead
> Create stalwart.md example_config

- README.md
- example_configs/stalwart.md
> Add link to README

- example_configs/stalwart.md
Update instructions for read_only bind
> Update stalwart.md instructions w/ read-only bind

- Cargo.lock
- Cargo.toml
- crates/domain-handlers/Cargo.toml
- crates/domain-handlers/src/handler.rs
- crates/domain-handlers/src/lib.rs
- server/Cargo.toml
- server/src/domain/ldap/group.rs
- server/src/domain/ldap/user.rs
- server/src/domain/ldap/utils.rs
- server/src/domain/mod.rs
- server/src/domain/sql_backend_handler.rs
- server/src/domain/sql_group_backend_handler.rs
- server/src/domain/sql_opaque_handler.rs
- server/src/domain/sql_schema_backend_handler.rs
- server/src/domain/sql_user_backend_handler.rs
- server/src/infra/access_control.rs
- server/src/infra/auth_service.rs
- server/src/infra/graphql/api.rs
- server/src/infra/graphql/mutation.rs
- server/src/infra/graphql/query.rs
- server/src/infra/ldap_handler.rs
- server/src/infra/ldap_server.rs
- server/src/infra/tcp_server.rs
- server/src/infra/test_utils.rs
- server/src/main.rs
Move traits related to backend handler to separate crate.
> domain-handlers: move backend handler traits to separate crate

- README.md
- example_configs/podman-quadlets/lldap-db.container
- example_configs/podman-quadlets/lldap.container
hello,
thank you for making such a great piece of software. i am using it via a rootless podman deployment and wanted to give back by including my quadlets with an example.
thank you again ^.^
> feat(examples): add example with podman quadlets for pgsql deployment w/ secrets

- .github/workflows/Dockerfile.dev
- .github/workflows/docker-build-static.yml
- Makefile
That will unlock the 2024 edition.
> chore: update lldap/rust-dev to 1.85

- Cargo.lock
- Cargo.toml
- app/Cargo.toml
- app/src/components/app.rs
- app/src/infra/api.rs
- crates/auth/Cargo.toml
- crates/domain-handlers/Cargo.toml
- crates/domain-model/Cargo.toml
- crates/domain/Cargo.toml
- crates/frontend-options/Cargo.toml
- crates/frontend-options/src/lib.rs
- migration-tool/Cargo.toml
- server/Cargo.toml
- server/src/infra/tcp_server.rs
- set-password/Cargo.toml
> app, server: Add an endpoint to fetch the frontend settings

- app/src/components/app.rs
> app: Remove max-width in main component

- example_configs/kimai.yaml
The PR fix the config example of Kimai, mentioned in #1142  .
> example_config: fix kimai.yaml

- server/src/domain/ldap/utils.rs
- server/src/infra/ldap_handler.rs
> ldap: add support for creating groups

- app/src/infra/form_utils.rs
> app: Fix email validation for groups

- app/src/components/app.rs
> app: Add a create user/group button at the top

- README.md
- example_configs/mailcow.md
A file for reference when using LLDAP in mailcow as LDAP.
> Mailcow LLDAP Example

- example_configs/podman-quadlets/lldap-backend.network
- example_configs/podman-quadlets/lldap-db.container
- example_configs/podman-quadlets/lldap-db.volume
- example_configs/podman-quadlets/lldap-frontend.network
- example_configs/podman-quadlets/lldap.container
- example_configs/podman-quadlets/readme.md
I had a hard time figuring out what to do to install lldap as a quadlet, as I'm very new to this container stuff.
I've formatted my notes into a readme for the quadlet service to guide user installation and added file for the volume and networks the container files referred to.
A thorough revision of the instruction I wrote would be welcome, as my confidence i didn't do something silly is low. If there's a mistake in there, then my setup suffer from it.
> Quadlet documentation and improvements

- README.md
- docs/faq.md
This is my understanding from #1196.
Please merge #1998 first.
I have no idea how to document reverse proxying of several instances so i just mentioned it's theoretically possible.
> Add FAQ about virtualhosts

- README.md
- docs/faq.md
Please merge #1198 first.
This is my way of expressing what was explained in #1197. If the content is wrong, or the phrasing is inappropriate feel free to edit the commit and force push to my branch before merging.
> Add FAQ about sustainability

- README.md
Nothing much, noticed while reading through
> fix: correct broken link in README

- crates/domain/src/deserialize.rs
- crates/domain/src/types.rs
- crates/graphql-server/src/api.rs
- crates/ldap/src/core/group.rs
- crates/ldap/src/core/user.rs
- crates/ldap/src/core/utils.rs
- crates/ldap/src/create.rs
- crates/ldap/src/delete.rs
- crates/ldap/src/handler.rs
- crates/ldap/src/modify.rs
- crates/ldap/src/password.rs
- crates/ldap/src/search.rs
- crates/sql-backend-handler/src/sql_backend_handler.rs
- crates/sql-backend-handler/src/sql_group_backend_handler.rs
- crates/sql-backend-handler/src/sql_user_backend_handler.rs
- server/src/auth_service.rs
- server/src/configuration.rs
- server/src/database_string.rs
- server/src/healthcheck.rs
- server/src/ldap_server.rs
- server/src/mail.rs
- server/src/main.rs
- server/src/sql_tcp_backend_handler.rs
- server/tests/common/env.rs
- server/tests/common/fixture.rs
- server/tests/common/graphql.rs
- server/tests/integrations.rs
- server/tests/ldap.rs
I noticed in #1216 clippy was failing, not only because of the PR changes.
In this PR i apply clippy suggestions to make it happy.
In the future we may want to pin clippy/fmt to a specific version to avoid breaking CI due to the Github Actions upgrading to a newer release.
> meta: Fix cargo clippy failures (format strings)

- .github/copilot-instructions.md
- .github/copilot-setup-steps.yml
- Cargo.lock
Add copilot-setup-steps.yml for GitHub Copilot agent environment setup
> Add comprehensive GitHub Copilot instructions for LLDAP repository

- .coderabbit.yml
- .github/workflows/docker-build-static.yml
- .github/workflows/rust.yml
- Cargo.toml
- crates/ldap/src/core/group.rs
- crates/ldap/src/core/user.rs
- crates/ldap/src/search.rs
- rust-toolchain.toml
This should help simplify the debug output.
> ldap: Simplify boolean expressions derived from filters

- README.md
Fixes https://github.com/lldap/lldap/issues/1233
> readme: Add a link to the configuration guide's readme
