lldap/lldap

Cargo.lock, Cargo.toml, app/src/login.rs, model/Cargo.toml, model/src/lib.rs, model/src/opaque.rs, src/domain/error.rs, src/domain/sql_backend_handler.rs, src/domain/sql_opaque_handler.rs, src/domain/sql_tables.rs, src/infra/configuration.rs, src/infra/db_cleaner.rs, src/infra/tcp_server.rs
opaque_ke changed their interface, update to the latest.
State needs to be kept from one step to the next during the login/registration. Rather than storing it in the database, send it (encrypted) to the client and back.
=> Update opaque and implement it without DB

src/domain/sql_opaque_handler.rs, src/main.rs
Commit e09c73e introduced a bug: when creating the admin account, we were no longer setting the password. This caused https://github.com/nitnelave/lldap/issues/24 because no password was set.
Fixes https://github.com/nitnelave/lldap/issues/24.
=> Set admin password when creating the user

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, app/Cargo.toml, app/queries/list_users.graphql, app/src/api.rs, app/src/create_user.rs, app/src/graphql.rs, app/src/graphql_api.rs, app/src/lib.rs, app/src/login.rs, app/src/user_table.rs, model/src/lib.rs, schema.graphql, src/domain/handler.rs, src/domain/sql_backend_handler.rs, src/domain/sql_tables.rs, src/infra/auth_service.rs, src/infra/cli.rs, src/infra/configuration.rs, src/infra/graphql/api.rs, src/infra/graphql/mod.rs, src/infra/graphql/query.rs, src/infra/ldap_handler.rs, src/infra/mod.rs, src/infra/tcp_api.rs, src/infra/tcp_backend_handler.rs, src/infra/tcp_server.rs, src/main.rs
This PR introduces a new endpoint as a GraphQL endpoint. That will help simplify introducing new REST methods (as GraphQL queries instead) and apply best practices.
Auth is still done separately using OPAQUE.
Eventually, `lldap_model` can be stripped to just the `opaque` module, since the rest of the data layout is communicated through the GraphQL schema only, simplifying documentation and client integration.
=> Implement a GraphQL endpoint and use it in the client

example_configs/keycloak.md
Something I noticed when setting up Keycloak. Setting just "admin" for the bind DN doesn't work. Instead you have to set the whole DN: `cn=admin,ou=people,dc=example,dc=com`
=> (Doc) Keycloak requires a full DN, not just the username

.github/workflows/docker.yml
Description updates doesn't work with app passwords.
=> Revert "github: Fix dockerhub description update"

Dockerfile, README.md, docker-entrypoint.sh, lldap_config.docker_template.toml
The script allows secrets to be set via env var defined filenames, and preserves the ability to pass different `lldap` subcommands/args via the docker command.
Documentation was updated to note the changes.
I took the liberty of pinning the upstream builder and base containers to alpine 3.14 since I noticed `alpine:latest` points to 3.15 while `rust:alpine` uses 3.14. I doubt its causing any issues, but it seems smart to control which versions are used rather than just pointing to latest. Let me know if you have a reason to keep it on latest and I can remove that change.
Addresses #84
=> Add an entrypoint script

Dockerfile, README.md, docker-entrypoint.sh, server/src/infra/cli.rs, server/src/infra/configuration.rs
By making the /app folder world-readable, we have nothing that ties us to the `app` user, so we can run the container as any user. This, and some added startup checks for permissions, should help with most issues that users experience.
Fixes #86
=> Fix issues with docker around users and permissions

lldap_config.docker_template.toml
**Issues**
- when getting help debugging on discord, it was mentioned that there was a verbose variable, which I added to the config file so other people can find it. 
- When trying to use a different administrator password, the web UI would use the changed password, but the bindDN password would always be `password`. 
**Fixes**
Updated the config file to have the correct value and added verbose.
=> fixed a typo and added verbose for future users to find

server/src/infra/ldap_handler.rs
=> ldap_handler: trim spaces in LDAP identifiers

server/src/domain/handler.rs, server/src/domain/sql_backend_handler.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/infra/tcp_backend_handler.rs
This should greatly expand to usability of group requests.
Fixes #103 .
=> Refactor groups to use filters internally

example_configs/authelia_config.yml, example_configs/bookstack.env.example, example_configs/dolibarr.md, example_configs/jellyfin.md, example_configs/jitsi_meet.conf, example_configs/keycloak.md, server/src/infra/ldap_handler.rs
This also changes the recommendation to use "uid" instead of "cn", since that's the meaning of the field. Using the actual value of "cn" will not actually work.
=> Accept "uid" in qualified name

server/src/infra/auth_service.rs, server/src/infra/graphql/mutation.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/main.rs
Fixes #176 .
This PR will create a group "lldap_readonly" on first run. Then the admin can create a user and add it to this group. It'll then be available both for web access (read-only except to update the details of the read-only user) and through LDAP (same, readonly except to change its own password).
=> Introduce a read-only user

example_configs/portainer.md
Add User filter search by groups, as some safety practice to group the user and filter user available in that group, rather than querying all user in ldap.
=> Add filter by group

README.md, example_configs/seafile.md
Readds both the previous example for Seafile and an alternative setup with Authelia as an intermediary.
=> Readd example config for Seafile

example_configs/grafana_ldap_config.toml
Adds a sample config for grafana. The comments are a mix of the default Grafana comments, and mine to help a bit.
=> docs: add Grafana config

Cargo.lock, app/src/components/change_password.rs, app/src/components/create_group.rs, app/src/components/create_user.rs, app/src/components/group_details.rs, app/src/components/group_table.rs, app/src/components/login.rs, app/src/components/logout.rs, app/src/components/remove_user_from_group.rs, app/src/components/reset_password_step1.rs, app/src/components/reset_password_step2.rs, app/src/components/user_details.rs, app/src/components/user_details_form.rs, app/src/components/user_table.rs, server/Cargo.toml, server/src/domain/sql_backend_handler.rs, server/src/domain/sql_opaque_handler.rs, server/src/infra/auth_service.rs, server/src/infra/db_cleaner.rs, server/src/infra/graphql/mutation.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/infra/ldap_server.rs, server/src/infra/logging.rs, server/src/infra/mail.rs, server/src/infra/sql_backend_handler.rs, server/src/infra/tcp_server.rs, server/src/main.rs
This PR instruments the code to add tracing events everywhere relevant. The events are then printed as a tree by tracing-forest, leading to a much-improved debug experience.
Fixes #17
=> Implement tracing logging

example_configs/authelia_config.yml
Authelia 4.36.1 changed the key for password resets. Fixed an error where the user: field was incorrectly set to uid=admin, resulting in a fatal error starting Authelia.
=> Update Authelia config for Authelia 4.36.1

.github/workflows/Dockerfile.ci, .github/workflows/Dockerfile.ci.alpine
Add volume to enable volume use case correctly.
```
volumes:
- lldap_data:/data 
```
As `/data` is empty by default, `lldap_config.toml` will be copied over. We can also use predefined `lldap_config` if needed, should we?
=> Volume support

docker-entrypoint.sh
Similar to LLDAP_JWT_SECRET and LLDAP_LDAP_USER_PASS, add option to use an
ENV variable to specify the file of the SMTP password:
LLDAP_SMTP_OPTIONS__PASSWORD_FILE
=> docker: Add support for SMTP password file

lldap_config.docker_template.toml, server/src/infra/configuration.rs, server/src/main.rs
Allows folks to set `ldap_user_email` alongside `ldap_user_dn` and `ldap_user_pass` via the configuration file / environment variables. I need to have my admin account provisioned with an email at creation, so this ends up being pretty useful :)
I'm having issues with building a Docker image / the linker (on Debian). but I don't think due to my changes? Please let me know if I've forgotten anything!
=> Set admin email from config

app/queries/get_group_details.graphql, app/queries/get_group_list.graphql, app/queries/get_user_details.graphql, app/src/components/group_details.rs, app/src/components/group_table.rs, app/src/components/user_details_form.rs, schema.graphql, server/src/infra/graphql/query.rs
These changes implement #211.
- UUID is added to the details view of users and groups.
- creation date is added as a column to the list of groups and to the groups detail view.
To do this I have added read only fields to the group details view using the same format that the user detail view has.
=>  Add UUID and creation date to the frontend

app/src/components/change_password.rs
The change password UI shows a password because the input field is "text" type.
In this PR, I tried to fix it by adding `input_type="password"` at `<Field />`.
=> Fix: Change input filed to password type in change_password ui

README.md
Docker compose will give a cryptic error message if `version` is omitted
=> Add version to docker-compose examples

Cargo.lock, migration-tool/Cargo.toml, migration-tool/src/lldap.rs
The response used to contain just the JWT, but now it's wrapped in JSON.
Fixes #282.
=> migration-tool: Extract the JWT from the JSON response

Cargo.lock, Cargo.toml, app/Cargo.toml, app/queries/get_user_details.graphql, app/src/components/create_user.rs, app/src/components/user_details.rs, app/src/components/user_details_form.rs, app/src/infra/common_component.rs, migration-tool/Cargo.toml, migration-tool/src/ldap.rs, migration-tool/src/lldap.rs, schema.graphql, server/Cargo.toml, server/src/domain/handler.rs, server/src/domain/sql_backend_handler.rs, server/src/infra/graphql/mutation.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/infra/ldap_server.rs
Does most of the heavy lifting required for #171 . With this, users can update their avatar in LLDAP and it is served in LDAP as `jpegPhoto` attribute.
Note that this only supports JPEG, not PNG.
This does not include support for the migration tool.
=> server: Add support for users' avatars in GrahpQL

server/src/domain/handler.rs, server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs, server/src/domain/ldap/utils.rs, server/src/domain/sql_tables.rs, server/src/domain/sql_user_backend_handler.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs
Now the columns are checked and mapped to user columns, to avoid any ambiguity.
Fixes #341.
=> server: Improve equality handling in filters

server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs, server/src/infra/ldap_handler.rs
If the filter name was not in the list of attributes to return, it wouldn't be counted as a valid attribute, meaning that the aliases of attributes were not recognized.
Fixes #351
=> server: fix handling of present filters

.github/workflows/Dockerfile.ci.alpine, .github/workflows/Dockerfile.ci.debian, Dockerfile, README.md
As PR title says, it will add `tzdata` package to the final docker image. Thanks to that, it will be easy to set timezone inside of the container, via `TZ=` env variable.
=> docker: add tzdata package, to support TZ env variable

README.md
as many variant of system, and different nodejs out there, define nodejs version to match the CI build.
=> Update readme to use nodejs 16

app/src/components/add_group_member.rs, app/src/components/add_user_to_group.rs, app/src/components/app.rs, app/src/components/change_password.rs, app/src/components/create_group.rs, app/src/components/create_user.rs, app/src/components/delete_group.rs, app/src/components/delete_user.rs, app/src/components/group_details.rs, app/src/components/group_table.rs, app/src/components/login.rs, app/src/components/reset_password_step1.rs, app/src/components/select.rs, app/src/components/user_details.rs, app/src/components/user_details_form.rs, app/src/components/user_table.rs, app/static/style.css
I spent some time today to try and improve the design of the front end of LLDAP. 
List of improvements that I can recall:
- Added colour to required asterisks
- Added padding to the footer
- Added bootstrap class to select elements
- Added various icons to buttons
- Fixed various button layouts
- Reworded some messages
- Moved around some form elements
Fixes #12
=> Front-end design improvements

lldap_config.docker_template.toml, server/src/infra/cli.rs, server/src/infra/configuration.rs, server/src/infra/ldap_server.rs, server/src/infra/tcp_server.rs
Introduce a new configuration variable called `host` to enable IPv6 support.
If by any means, the naming of the variable should be adjusted, or a bool is preferred to toggle this behavior, I am for sure willing to adjust this ;)
Resolves #359
=> server: make `host` configurable to enable IPv6 support

.github/workflows/Dockerfile.dev, .github/workflows/docker-build-static.yml
Get ready for #382 and update Rust in docker to fix (https://github.com/nitnelave/lldap/actions/runs/3544340544/jobs/5951515771)
=> docker: update Rust to v1.65.0

server/src/domain/sql_group_backend_handler.rs, server/src/domain/sql_opaque_handler.rs, server/src/domain/sql_user_backend_handler.rs
It used to try to set all user IDs to the same, which would fail if there is more than 1 user.
=> server: fix user password setting

Dockerfile
This was broken by #382 - sea-orm requires rust 1.65. This version of the rust-alpine container uses 1.66.
=> Fix version in base dockerfile

.github/workflows/Dockerfile.ci.alpine, .github/workflows/Dockerfile.ci.debian, .github/workflows/docker-build-static.yml
* Use nitnelave/rust-dev:latest for all job
* simplify artifacts download, no more per arch downloading
* add `rustup target add wasm32-unknown-unknown` on ui build, will this affect anything?
* update actions/cache version
* modify release to all in one compressed
=> simplify artifacts download and some other things

lldap_config.docker_template.toml, server/src/infra/cli.rs, server/src/infra/configuration.rs, server/src/infra/mail.rs
Allows to use SMTP without TLS (useful for internal relays). I also noticed, that `port` is ignored, so I added it as well.
=> add option to use insecure SMTP connection

app/src/lib.rs, migration-tool/src/main.rs, server/src/domain/sql_migrations.rs, server/src/main.rs
The clippy::uninlined_format_args warning in 1.67 was downgraded to pedantic in 1.67.1 due to lack of support in rust-analyzer, so we're not updating that one yet.
=> server: fix clippy warning

example_configs/jellyfin.md
I found it lacking an explanation of the "Admin Base DN" Setting of the LDAP Plugin. Hope this can help people in the future
=> Added explanation to Jellyfin Docs

app/src/components/change_password.rs
Change input field type for field old_password from its default "text" to "password"
=> Fix: Change input field to password type in change_password ui

app/src/components/app.rs, app/src/components/reset_password_step2.rs, server/src/infra/auth_service.rs, server/src/infra/mail.rs, server/src/infra/tcp_server.rs
This makes the configuration more robust to a trailing slash in the domain, and improves the error messages when clicking on a non-existing or expired token.
=> Improve reset email errors

.github/workflows/Dockerfile.dev, Cargo.toml, Dockerfile, app/build.sh, app/index.html, app/index_local.html, app/src/infra/modal.rs, app/static/main.js, server/src/infra/tcp_server.rs
This way we get rid of the npm dependency (it's not needed anyway), and we reduce the file size served (2.6MB -> 700kB)
=> app: get rid of rollup, gzip the wasm

.github/workflows/Dockerfile.ci.alpine
On alpine dockerfile got old `$CONTAINERUSER` rather than $USER, oversighted on last overhaul, and undetected because our `docker-entrypoint.sh` correct this on runtime. Then detected after run without `docker-entrypoint.sh` while supporting https://github.com/nitnelave/lldap/pull/475
=> Correctly set permission on `/app` path and `entrypoint`

example_configs/dex_config.yml
As discussed on discord, the usserAttr needs to be the full DN, as the search does not work:
```
❯ ldapsearch -x -H ldap://localhost:3890 -D "cn=admin,ou=people,dc=example,dc=com" -b "ou=groups,dc=example,dc=com" -W "member=bob"
Enter LDAP Password: 
#
#
search: 2
result: 53 Server is unwilling to perform
text: Unsupported group filter: while parsing a user ID: Missing DN value
```
=> Fix dex config example

.github/workflows/docker-build-static.yml
Fixes: https://github.com/lldap/lldap/issues/527
The requested `ghcr.io/nitnelave/lldap` container image is commented out and can be uncommented if needed because it needs to have the repo owner to create a secret named `NITNELAVE_GITHUB_TOKEN`.
=> github: also push to ghcr.io

docs/migration_guides/v0.5.md, server/src/domain/sql_migrations.rs, server/src/domain/sql_tables.rs
Example error message, from the test:
```
2023-04-14T09:44:38.905177Z  INFO lldap::domain::sql_migrations: Upgrading DB schema from version 1
2023-04-14T09:44:38.905208Z  INFO lldap::domain::sql_migrations: Upgrading DB schema to version 2
2023-04-14T09:44:38.910783Z  INFO lldap::domain::sql_migrations: Upgrading DB schema to version 3
2023-04-14T09:44:38.924604Z  INFO lldap::domain::sql_migrations: Upgrading DB schema to version 4
2023-04-14T09:40:08.738013Z  WARN lldap::domain::sql_migrations: Found several users with the same email:
2023-04-14T09:40:08.738613Z  WARN lldap::domain::sql_migrations: Email: bob@bob.com
2023-04-14T09:40:08.738642Z  WARN lldap::domain::sql_migrations:     User: bob
2023-04-14T09:40:08.738659Z  WARN lldap::domain::sql_migrations:     User: bob2 …
```
=> server: Improve the error message in case of duplicate emails

lldap_config.docker_template.toml
found out about `LLDAP_KEY_FILE` by trial and error, figured `LLDAP_KEY_SEED` by inference
=> correct env var names in docker template toml

example_configs/jellyfin.md
The LdapAdminBaseDN either doesn't work properly or is used incorrectly here.
This change will make it work.
see: 
- https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/145
=> Update jellyfin.md example

.github/workflows/docker-build-static.yml
* mariadb:latest v11 container image, don't have reference to `mysql` anymore, update command from `mysqladmin` to `mariadb-admin`
=> actions: update mariadb healthcheck

example_configs/keycloak.md
Keycloak seems to default to "First name" being `cn` which LLDAP uses for Display Name, resulting in Users getting duplicated display names in Keycloak (like First Last Last), or missing their first name entirely (when they have no DIsplay Name in LLDAP).
This just updates the example config to provide instructions on changing the attribute mapping in Keycloak to fix this.
=> Update Keycloak example for name attributes

README.md, example_configs/squid.md
Squid as a caching proxy that uses LDAP to authenticate users. The procedure configures that only authenticated users can use the proxy.
=> example config for squid

schema.graphql, server/src/domain/handler.rs, server/src/domain/ldap/utils.rs, server/src/infra/access_control.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/infra/mod.rs, server/src/infra/schema.rs, server/src/infra/test_utils.rs
I chose to decouple the domain-level configurable attributes, and the public-viewable schema which includes the attributes that are not stored as "user attributes". All the "hardcoded" attributes will be available as fields from grahpql, and the non-hardcoded will be only in the "user_attributes" (coming) field.
In terms of permissions, only users who have the permissions to see all the users (admin, password manager or readonly) can see the schema. Regular users cannot (they wouldn't have much use for it, and that way I don't have to filter the fields they're not allowed to see).
=> Add a graphql method to get the schema

.github/workflows/Dockerfile.dev
Tasks:
Deprecated warning:
* Warning: the following packages contain code that will be rejected by a future version of Rust: nom v2.2.1
Related:
* https://github.com/lldap/lldap/pull/584
PS: Locally tested that armv7 musleabihf compiled successfully
=> dev image: prep for 1.71

app/src/components/change_password.rs, app/src/components/create_user.rs, app/src/components/reset_password_step2.rs, auth/src/opaque.rs, server/src/domain/sql_backend_handler.rs, server/src/domain/sql_opaque_handler.rs, server/src/infra/ldap_handler.rs, set-password/src/main.rs
Fixes #620 
Note that in verbose logging mode, the password will be written in clear in the logs. That was the original motivation for only supporting the extended operation.
=> ldap: Add support for modifying the password with a modify operation

server/src/infra/cli.rs
Otherwise the two parsings of STARTTLS vs start-tls conflict.
=> server: fix smtp encryption parsing

example_configs/home-assistant.md
The name of the script downloaded from Github did not match the example code and tripped me up until I noticed. This changes "lldap-auth.sh" to "lldap-ha-auth.sh" in the examples.
=> Update script names in home-assistant example

example_configs/zabbix-web.md
Tested with LLDAP by me. Note that I currently use LTS (6.0) not latest (6.4), so while I see that there are many more LDAP options in later Zabbix Web versions, I did not test them and I put a version note to that effect in the doc.
=> example_configs: Add Zabbix Web example

.github/workflows/Dockerfile.ci.alpine, .github/workflows/Dockerfile.ci.debian, .github/workflows/docker-build-static.yml
~~Building with gnu compiler~~
Issue after change
```
= note: LC_ALL="C" PATH="/home/debian/rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/debian/rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/self-contained:/opt/aarch64-linux-musl-cross/:/opt/aarch64-linux-musl-cross/bin/:/opt/x86_64-linux-musl-cross/:/opt/x86_64-linux-musl-cross/bin/:/home/debian/cargo/bin/:/home/debian/.local/bin:/home/debian/.local/lib:/home/debian/.local/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" VSLANG="1033" "aarch64-linux-gnu-gcc" "/home/debian/rustup/toolchains/1.69.0-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o" …
```
=> github: enable armv7 musl build

set-password/src/main.rs
The password length limitation is arbitrary and non-configurable, and there are legitimate requirements to set a password shorter than 8 characters. This change will make it simple to achieve without the need for a third party tool.
I would update the web UI code also, but am unfamiliar with Rust and the wider LLDAP project to confidently make the change and not break something. The change for this tool appears simple, however.
=> Remove password length limitation in lldap_set_password tool

app/src/components/app.rs, docs/database_migration.md, example_configs/lldap.service, example_configs/nextcloud_oidc_authelia.md
There were still some references to the old repository at `nitnelave/lldap` _(most notably in the footer of the web interface)_.
=> chore: update repository references

.github/workflows/docker-build-static.yml
fixes #613 
adds additional date tag when publishing "latest" docker images
=> add date-based tagging to docker matrix jobs

README.md
Currently README.md mentions Docker, Kubernetes, and (manually) from source as installation options. Since lldap is showing up in the Arch User Repository for Arch Linux, I thought it would be handy to have a section in the documentation dedicated to installation of lldap from package repositories. I put a warning on top of this part of the documentation that issues with downstream packages should be reported downstream and not here.
Full disclosure :smile::
I am the author of the [`lldap-bin`](https://aur.archlinux.org/packages/lldap-bin) AUR package description. It would be helpful to point users to this and the other lldap package descriptions if they are using Arch Linux. And hopefully lldap will also be available directly in other distributions.
=> Documentation: add installation instructions to install from package repositories

example_configs/jenkins.md
Referring to the official documentation, the Manager DN should contain 'dc'
> If your LDAP server doesn't support [anonymous binding](http://www.google.com/?q=LDAP+anonymous+bind) (IOW, if your LDAP server doesn't even allow a query without authentication), then Jenkins would have to first authenticate itself against the LDAP server, and Jenkins does that by sending "manager" DN and password.
A DN typically looks like CN=MyUser,CN=Users,DC=mydomain,DC=com although the exact sequence of tokens depends on the LDAP server configuration. It can be any valid DN as long as LDAP allows this user to query data.
> This configuration is also useful when you are connecting to Active Directory from a Unix machine, as AD doesn't allow anonymous bind by default. But if you can't figure this out, you …
=> Use correct Manager DN in Jenkins configuration

lldap_config.docker_template.toml
Updated the config template to make it clear that the user should not set LLDAP server to listen on localhost if it is running in a docker container as it would then not be able to accept connections originating from outside the container.
=> Update config with clearer instructions for setting listen address in a docker setup

app/index.html, app/src/components/app.rs, app/src/infra/api.rs, app/src/infra/cookies.rs, server/src/infra/auth_service.rs, server/src/infra/tcp_server.rs
This adds support for placing lldap on a sub-path.
To use it, a User needs to set the `http_url` setting to a URL with a sub-path (`http://example.com/lldap`) and setup the reverse-proxy to strip the sub-path.
Caddy example:
```
handle_path /lldap* {
reverse_proxy http://127.0.0.1:17170
}
```
Future Work:
Currently, the sub-path is injected every time `index.html` and `main.js` are called, but this could be cached instead.
I tried it, but I never used actix before, and thus couldn't make it work.
=> app: make it possible to serve lldap behind a sub-path

server/src/domain/handler.rs, server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs, server/src/domain/ldap/utils.rs, server/src/domain/model/group_attribute_schema.rs, server/src/domain/model/group_attributes.rs, server/src/domain/model/groups.rs, server/src/domain/model/user_attribute_schema.rs, server/src/domain/model/user_attributes.rs, server/src/domain/model/users.rs, server/src/domain/schema.rs, server/src/domain/sql_backend_handler.rs, server/src/domain/sql_group_backend_handler.rs, server/src/domain/sql_migrations.rs, server/src/domain/sql_schema_backend_handler.rs, server/src/domain/sql_tables.rs, server/src/domain/sql_user_backend_handler.rs, server/src/domain/types.rs, server/src/infra/access_control.rs, server/src/infra/auth_service.rs, server/src/infra/configuration.rs, server/src/infra/graphql/mutation.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs, server/src/infra/ldap_server.rs, server/src/infra/test_utils.rs, server/src/main.rs
In addition, group names and emails keep their casing.
Fixes #666
=> server: make attributes names, group names and emails case insensitive

Cargo.lock, server/Cargo.toml, server/src/domain/sql_migrations.rs, server/src/domain/sql_tables.rs, server/src/infra/cli.rs, server/src/infra/configuration.rs, server/src/main.rs
This checks that the private key used to encode the passwords has not changed since last successful startup, leading to a corruption of all the passwords. Lots of common scenario are covered, with various combinations of key in a file or from a seed, set in the config file or in an env variable or through CLI, and so on.
Fixes #747
=> server: Add a check for a changing private key

server/src/domain/handler.rs, server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs, server/src/domain/ldap/utils.rs, server/src/domain/sql_group_backend_handler.rs, server/src/infra/graphql/query.rs, server/src/infra/ldap_handler.rs
This consolidates both user and group attributes in their map_{user,group}_attribute as the only point of parsing. It adds support for custom attribute filters for groups, and makes a SubString filter on an unknown attribute resolve to just false.
It should help with #739
=> server: clean up the attributes, relax the substring filter conditions

example_configs/mailserver.md
* Fixes following issues:
- double braces around mail= filter cause: 
ldap_search_ext: Bad search filter (-7)
- too wide/upper level base DN cause, changed to ou= level helps   
result: 53 Server is unwilling to perform 
text: Unsupported group attribute for substring filter: "mail"
=> Fix docker-mailserver example

app/src/components/add_group_member.rs
=> app: default to user_id if display_name is empty, when adding users to groups

example_configs/pfsense.md
Add warning about `Organizational Units` that will fail. 
Minor formating
=> pfsense.md, add warning about error about `Organizational Units` 

example_configs/nextcloud.md
Context for why I believe this is a good idea:
- When logging with a new user "ibizaman" through the database backend, the ID used by Nextcloud is `ibizaman`.
- Through the LDAP backend, Nextcloud chooses the `UUID` field.
- Through the SSO backend, integrated with LDAP, Nextcloud chooses `ibizaman`.
I noticed this issue while migrating users from database backend, to LDAP backend, to SSO backend where the ID was inconsistent. Also, it means that if a user was created through LDAP and tries to login through SSO, a new user will be created!
This inconsistency makes no sense IMO. By overriding the `UUID` field to be the `user_id` field, the ID assigned to a new user is consistent whatever the backend used.
=> Add user_id for nextcloud example

example_configs/mailserver.md
Without the protocol specified, Mailserver throws an error
=> Include protocol in Mailserver example

example_configs/authelia_config.yml
example_config: adjusted address and attributes for authelia 5.0.0 compliance
Fix #929
- the `url` property becomes `address`
- user attributes changed format from `username_attribute` & `group_name_attribute` to `attributes.username` & `attributes.group_name`
All attributes defined by [Authelias documentation](https://www.authelia.com/configuration/first-factor/ldap/#configuration) are listed but any which were not previously used are commented out
=> example_config: adjusted address and attributes for authelia 5.0.0 compliance

scripts/bootstrap.sh
**Overview**
Fix user id existence check by doing exact match instead of substring contains.
Fixes #933
=> Fix bootstrap.sh user id existence check

example_configs/dex_config.yml
Host and optional port of the LDAP server in the form "host:port".
=> docs: fix example of ldap dex integration

server/src/infra/graphql/query.rs
Note the `std::mem::take(&mut user.attributes)` further up that zeroes out `user.attributes`.
Fixes #822, cherry-picked from #942.
=> fix: Lookup first_name/last_name in the right list of attributes

Cargo.lock
Fixes building with Rust 1.80.0.
See https://github.com/rust-lang/rust/issues/127343.
Closes: https://github.com/lldap/lldap/issues/945
=> cargo: update time

README.md
This PR will extend the `install from a package repository` section to give more information about each individual distro.
Since all prebuilt packages are contributed by third parties (unofficial) the maintainer, support channels, and even the available sub-packages differ for every distro. So I tried to create a meaningful section for every distro that contains all relevant information.
I was not sure who feels responsible for the `Arch` repository, it was added to the readme by @Zepmann , but `AUR` shows another name as the maintainer. For now I listed @Zepmann is maintainer.
=> Improve the package repository section in README.md

server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs, server/src/domain/ldap/utils.rs, server/src/infra/ldap_handler.rs
This should help when the client sends some invalid-looking queries as part of a bigger filter
Solves #949
=> server: Add support for memberOf with plain user names, relax hard errors

Cargo.lock
The **whoami** crate did not have support for **illumos** systems in the current pinned version (1.3.0) so I bumped it with `cargo update -p whoami` to 1.5.1 and now everything builds and `cargo test` passes on my system:
```
$ cat /etc/os-release
NAME="Helios"
PRETTY_NAME="Oxide Helios 2"
CPE_NAME="cpe:/o:oxide:helios:2:0"
ID=helios
VERSION=2
VERSION_ID=2
BUILD_ID=2.0.2023.06.21
HOME_URL="https://oxide.computer/helios/"
SUPPORT_URL="https://oxide.computer/helios/"
BUG_REPORT_URL="https://github.com/oxidecomputer/helios/issues/new"
$ uname -a
SunOS vulcan 5.11 helios-2.0.22694 i86pc i386 i86pc
```
=> update whoami dependency to fix illumos build

server/src/infra/mail.rs
SMTP docs for many email providers use SSL to mean SSL/TLS, and TLS to mean STARTTLS, causing endless confusion. This should hopefully help.
=> server: clarify SMTP error message

server/src/domain/error.rs, server/src/domain/sql_opaque_handler.rs, server/src/infra/auth_service.rs
That way, it becomes doable to automate log monitoring for too many failed login attempts.
Note that OPAQUE logins don't keep the associated username, so they cannot log which user successfully logged in or not; in addition, the client knows between the 2 queries whether the password was correct without having to tell the server.
Sample logs:
- Login through LDAP (failure then success):
```
2024-09-26T18:21:40.971371306+00:00  INFO     LDAP session [ 647ms | 0.06% / 100.00% ]
2024-09-26T18:21:40.971628975+00:00  INFO     ┝━ LDAP request [ 646ms | 99.94% ]
2024-09-26T18:21:40.972371031+00:00  INFO     │  ┝━ ｉ [info]: Login attempt for "admin" | log.target: "lldap::domain::sql_opaque_handler" | log.module_path: "lldap::domain::sql_opaque_handler" | log.file: …
```
=> server: Clarify logging of login attempts and failures

server/src/domain/sql_opaque_handler.rs, server/src/infra/auth_service.rs
Sample logs:
- Reset
```
2024-09-26T20:30:25.928317158+00:00  INFO     ｉ [info]: Successfully (re)set password for "test_user"
```
- OPAQUE (silent) failure, then success:
```
2024-09-26T20:30:56.908559850+00:00  INFO     ｉ [info]: OPAQUE login attempt for "admin"
2024-09-26T20:31:03.074156475+00:00  INFO     ｉ [info]: OPAQUE login attempt for "admin"
2024-09-26T20:31:03.600463950+00:00  INFO     ｉ [info]: OPAQUE login successful for "admin"
```
=> server: Add logging for password resets, add name for successful opaque logins

example_configs/bootstrap/bootstrap.md, scripts/bootstrap.sh
* Moved default bootstrap dirs into single /bootstrap parent dir in order to have single docker volume bind
* Added default values for LDAP url and credentials - same as default lldap values
* Added support for bootstrapping schemas
Place schema files under /bootstrap/(user|group)-schemas/*.json
Sample content:
```
[
{
"name" : "test_attrib",
"attributeType" : "STRING",
"isEditable" : true,
"isList" : false,
"isVisible" : true
}
]
```
=> Add support for bootstrapping schemas

server/src/infra/logging.rs
If the variable LLDAP_RAW_LOG is set, the logs will be both formatted with tracing_forest and printed raw
=> server: Add a way to print raw logs

.github/workflows/Dockerfile.ci.alpine-base, .github/workflows/Dockerfile.ci.debian-base
fix #921 
Not sure if there is a separate Dockerfile for the rootless variant?
=> Dockerfile: add jq/jo/curl, required by bootstrap.sh (fix #921)

example_configs/keycloak.md
It should be `givenName` instead of `givenname`. Using the later one, will result in Keycloak bugging out during the sync process, and henceforth displaying an empty user list.
=> fix: typo for first name attribute

server/src/infra/database_string.rs, server/src/main.rs
Several writer connections can lock the DB and cause other inserts to fail.
A single connection should be enough given the usual workloads
Fixes #1021
=> server: Only use a single connection with SQlite

README.md
Cleaned up the Arch Linux section. Added a link to the discussions support thread.
An important clarification taken into account is that I only maintain two out of three packages in AUR. For lldap-git support will be more limited since I can only act as a liaison between upstream and lldap-git in AUR.
=> Updated README.md Arch Linux install-from-repository section

example_configs/authelia_config.yml
This updates the Authelia config example to use the built-in `lldap` implementation. I tried to keep only the settings that are specific to LLDAP, and also clarify which settings are optional.
Note I haven't tried the TLS/LDAPS option myself, so I'm assuming that Authelia's TLS settings will work with LLDAP.
=> Update Authelia config example

server/src/domain/ldap/group.rs, server/src/domain/ldap/utils.rs, server/src/infra/ldap_handler.rs
Adds support for querying groups by their Id's in LDAP search filters. 
Support is added for both group_id and groupid, the former being shown on the group schema overview, and the latter being supported by openldap's C library, and thus more clients.
=> Add support for querying GroupId with LDAP filters

app/src/components/fragments/attribute_schema.rs, app/src/components/fragments/mod.rs, app/src/components/group_schema_table.rs, app/src/components/mod.rs, app/src/components/user_schema_table.rs, app/src/infra/attributes.rs, app/src/infra/mod.rs
A number of the hardcoded attributes displayed in the User and Group schema overviews were using aliases which contain underscores, which is not always completely supported by clients. Therefore, this commit changes the primary alias for each attribute to be one without underscores.
To reduce confusion with this change, and also improve the visibility of available aliases, this commit also includes a list of each alias, for each hardcoded attribute. This list will also include the old primary aliases.
This PR has been marked as a draft, as it depends on somewhat on [PR #1081](https://github.com/lldap/lldap/pull/1081)
=> Change default alias for User & Group schema attributes

Cargo.lock, app/Cargo.toml, app/src/components/create_group_attribute.rs, app/src/components/create_user_attribute.rs, app/src/components/fragments/attribute_schema.rs, app/src/components/group_schema_table.rs, app/src/components/user_schema_table.rs, server/Cargo.toml, server/src/infra/graphql/mutation.rs, validation/Cargo.toml, validation/src/attributes.rs, validation/src/lib.rs
This commit adds support for basic validation of attribute names at creation, and also in the schema overview. Both user and group attributes are validated with the same rules.
For now, attribute names will be considered valid, if they only contain alphanumeric characters.
Validation has been added the following places:
- In graphql API, for creation of both user and group attributes. Request will be rejected, if attribute name is invalid.
- In frontend, before submitting a request to create a new user or group attribute. Rejection here will show an error message including a list of the invalid characters used.
As this change adds stricter validation to attributes, and, since the rationale for this is partly compatibility with other LDAP systems, this change also adds a warning in the …
=> Add validation and error/warning messages for attribute names (#1072)

server/src/infra/tcp_server.rs
Had changed behaviour to serve the gz compressed wasm package with the uncompressed handler.
=> Fix serving of frontend after PR #1079

server/src/domain/ldap/group.rs, server/src/domain/ldap/user.rs
When debugging lldap logs I recognized that the output looks strange using syslog and grafana.
There are two outputs for each warnings, the first one contains the visible `\n\` sequence.
Additional the user message contains the string ` group attribute` .
Be aware: I've no clue about rust development!
=> Cleanup log messages for ignored attribute warnings

crates/domain/src/requests.rs, schema.graphql, server/src/domain/sql_backend_handler.rs, server/src/domain/sql_user_backend_handler.rs, server/src/infra/graphql/mutation.rs, server/src/infra/ldap_handler.rs
The fields first_name, last_name, and avatar have all been moved to regular attributes in the database, and are available through the GraphQL API as such as well. This commit removes the legacy fields for each on the internal CreateUserRequest type, leaving these to only be updateable through attributes.
The fields are still available in the GraphQL CreateUserInput type, preserving backwards compatiblity, and if set, they will be used for the corresponding attribute values. If both fields and attributes are set, the values given through attributes will superceed the fields, and be used. This change also fixes a bug, where creation of a user would fail if either of these attributes were set as both attribute and field, as it would attempt to insert the attribute twice, violating a unique …
=> server: remove deprecated fields from CreateUserRequest

README.md, example_configs/quay.md
This PR introduces a basic LDAP configuration for Project Quay deployments.
=> Add Project Quay example config

README.md
Hi,
this adds a small clarification to the README regarding users in the `lldap_password_manager` group not being able to change passwords of admins in the `lldap_admin` group.
=> readme: clarify password change permission for admin users

example_configs/pam/nslcd.conf
If a user uses the template nslcd.conf as per the PAM configuration guide group members are not correctly mapped.
Noted when querying groups via `getent group` which was returning `error writing group entry: Invalid argument` for ldap groups with group members.
=> example_configs: Fix nslcd group member mapping.

scripts/bootstrap.sh
Fixes #1088 
Update the bootstrap script to include additional attributes for users and groups.
I've done light testing on these changes but they seem to work fine for all supported data types.
Currently I use this script by mapping it to a separate folder with docker (i.e. -v "<script_location>":/scripts) and executing it from there.
=> Include custom attributes when bootstrapping user and group configs

example_configs/grocy.md
I changed the port in the Grocy example config to 3890, so it is the default LLDAP port.
=> Use default LLDAP port in Grocy example config

Dockerfile
The Dockerfile currently fails to build the project as the version of rust used in Alpine 3.18/3.19 is no longer supported by many of the dependencies used in LLDAP.
- Update Alpine Version to 3.21
- Migrate Docker `ENV` syntax from deprecated to new style of ENV
=> Docker Build Fixes

README.md, example_configs/freebsd/freebsd-install.md, example_configs/freebsd/rc.d_lldap
The support in FreeBSD package system should help us on getting rid of downloading tarball.
Here is the corresponding PR in FreeBSD port: https://reviews.freebsd.org/D49986
Still waiting to be approved.
=> example_configs: correct the manual for pkg support in FreeBSD

example_configs/authelia_config.yml
Authelia when installed via helm by default looks for users in the `Users` OU.  It supports changing this configuration via the `additional_users_dn` property.  Set this to match what lldap expects.
=> Update authelia configuration

example_configs/wikijs.md
The Wikijs example has erroneous search strings because closing curly brackets are missing in two cases.
=> Add missing closing curly brackets

scripts/bootstrap.sh
In the bootstrap script, instead of embedding the password in the config file directly, allow to pass a path to a file which contains the password.
This was tested in a NixOS draft PR https://github.com/NixOS/nixpkgs/pull/425923.
=> bootstrap: allow to give password from a file

crates/ldap/src/core/utils.rs, crates/ldap/src/search.rs
Fixes #1203.
This PR implements all attributes used in a regular LLDAP search response:
```
ldapsearch -H ldap://localhost:3890 -D uid=admin,ou=people,dc=example,dc=com -w password -o ldif-wrap=no -b dc=example,dc=com
```
I walked through a response and comprised the following list of missing `attributeTypes` definitions and their `ldapSyntaxes` and `matchingRules`. **Please check if I didn't miss any**
We might technically not need the `matchingRules`, however I thought it might be good to be as complete as possible.
I also (maybe as a temporary solution) changed the start number of custom LLDAP attributes from 2.x to 10.x, as we're currently not using that range at all and we are now using the 2.x range with the RFC attribute defintions.
The list:
_Note that these entries were derived …
=> ldap: Add missing subschema entries

crates/ldap/src/search.rs
From https://github.com/lldap/lldap/pull/1250 :
The memberOf attribute was missing from the LDAP schema definition returned by LLDAP, causing some LDAP clients (like Python's ldap3 library) to reject searches using the memberOf attribute with an LDAPAttributeError.
While the memberOf functionality worked correctly for searches and filters, the attribute was not declared in the schema's attributeTypes section, leading to client-side validation failures.
This change adds the memberOf attribute definition to the hardcoded attributes list in the LDAP schema response with:
-     OID: 1.2.840.113556.1.2.102 (Microsoft's standard OID for memberOf)
-     Distinguished Name syntax for group DN values
-     Multi-valued attribute (no SINGLE-VALUE restriction)
-     NO-USER-MODIFICATION flag …
=> Add memberOf attribute definition to LDAP schema

example_configs/podman-quadlets/readme.md
Several "podman" command should have been "systemctl" from the start.
That's my mistake, i'm sorry i didn't catch it earlier.
=> Correct mistake in the quadlet readme

.devcontainer/Dockerfile, .github/workflows/Dockerfile.dev, .github/workflows/docker-build-static.yml, .github/workflows/rust.yml, Cargo.toml, app/Cargo.toml, app/src/components/form/file_input.rs, app/src/infra/attributes.rs, app/src/lib.rs, crates/access-control/Cargo.toml, crates/auth/Cargo.toml, crates/domain-handlers/Cargo.toml, crates/domain-model/Cargo.toml, crates/domain/Cargo.toml, crates/frontend-options/Cargo.toml, crates/graphql-server/Cargo.toml, crates/ldap/Cargo.toml, crates/ldap/src/search.rs, crates/opaque-handler/Cargo.toml, crates/sql-backend-handler/Cargo.toml, crates/test-utils/Cargo.toml, crates/validation/Cargo.toml, migration-tool/Cargo.toml, rust-toolchain.toml, server/Cargo.toml, server/tests/common/graphql.rs, set-password/Cargo.toml
- Upgrades Rust from 1.85 to 1.89 across Docker files, CI workflows, and MSRV
- Adds `rust-toolchain.toml` to pin project toolchain version
- Modernizes code with let-chain syntax replacing nested if-let patterns
- Updates lifetime annotations in attribute description functions
=> chore: upgrade Rust toolchain to 1.89 and modernize code with let-chains

.envrc, .gitignore, CONTRIBUTING.md, docs/nix-development.md, flake.lock, flake.nix
- Add Nix flake and lockfile for reproducible development environments
- Document Nix-based setup in `docs/nix-development.md`
- Add `.envrc` for direnv integration and update `.gitignore` for Nix/direnv artifacts
- Reference Nix setup in CONTRIBUTING.md
=> chore: add Nix flake-based development environment

example_configs/open-webui.md
Added open-webui.md.
Environment Variables where directly taken from the logs. Version v0.6.26.
Other then additionally mounting the ca chain into the container (with appropriate rights) there were not additional steps required. The ownership of the ca chain will get changed to `chown 501:`.
=> document: Simple `LDAPS://` configuration for Open WebUI

example_configs/portainer.md
Updated group membership and filter attributes in portainer.md The current descriptions is wrong, and will make portainer try to assign "group" to be a member of "group" instead of the assign the "user" to be a part of "group"
=> Modify group membership and filter attributes to be correct for portainer description
